apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    nodeSelector:
      hardware: gpu
  - name: nginx
    image: nginx:stable-perl
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
    